# Generated by Django 3.1.3 on 2020-11-27 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from dbview.helpers import CreateView


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('author',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status',
                 models.CharField(choices=[('NORUN', 'NORUN'), ('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='runs', to=settings.AUTH_USER_MODEL)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs',
                                                to='tcm.testcase')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        CreateView(
            name='TestCaseStat',
            fields=[
                ('test_case',
                 models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True,
                                      serialize=False, to='tcm.testcase')),
                ('status',
                 models.CharField(choices=[('NORUN', 'NORUN'), ('PASS', 'PASS'), ('FAIL', 'FAIL')], max_length=10)),
                ('last_executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
